---
title: "About the workshop"
---

National Park managers across the country are confronted with increasingly complex and challenging issues that require broad-based understanding of the status and trends of park resources as a foundation for making decisions, working with other agencies, and communicating with the public to protect park natural systems and native species. Monitoring data help to define the normal limits of natural variation in park resources, detect long-term environmental change, provide insights into the ecological consequences of change, and inform stakeholders and the general public of changes in resource conditions that may be caused by stressors such as climate change that operate at regional and global scales.

In this context, the National Park Service (NPS) Inventory and Monitoring (I&M) Networks are charged with implementing a long-term ecological monitoring program to assess status and trends in the condition of natural resources across NPS units. Each of the five Intermountain Region I&M networks has developed a monitoring protocol for upland vegetation and soils, although the sampling designs, monitoring methods, and specific objectives differ somewhat from network to network. The networks have been collecting monitoring data for a number of years (ranging from 5-9 years) using a variety of rotating panel designs. Conservation Science Partners (CSP) is providing statistical guidance and support for each of several phases of the analysis process, which will be organized around two workshops with intervening statistical consultation. Two principal objectives of this effort are to: 1) develop and conduct statistical analyses to examine long-term trends of complex survey designs in upland monitoring for five I&M networks; and 2) discuss, consult and consider different alternatives to network specific long-term monitoring statistical issues. Ultimately, the I&M networks—with the support of CSP—seek to describe the status and trends of numerous vegetation metrics at both functional group and species levels (e.g., foliar cover, density, frequency) and to relate them to environmental factors and system drivers on NPS lands.

The five participating Intermountain Region Inventory and Monitoring networks include:

* Northern Colorado Plateau Network (NCPN)
* Greater Yellowstone Network (GRYN)
* Southern Colorado Plateau Network (SCPN)
* Rocky Mountain Network (ROMN)
* Chihuahuan Desert Network (CHDN)
<br><br>

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=FALSE, message=FALSE)
```

<!-- ```{r} -->
<!-- # Read the chunk (does not run the code). -->
<!-- knitr::read_chunk(file.path(PROJ_ROOT, 'map.R')) -->
<!-- ``` -->

<!-- ```{r} -->
<!-- # Run the chunk. -->
<!-- <<leaflet_map>> -->
<!-- ``` -->

<iframe src="https://dl.dropboxusercontent.com/u/4920360/sev_leaflet_map/index.html" 
height="700" width="100%"
        scrolling="no" seamless="seamless"
        frameBorder="0"></iframe>

<!-- ## Survey design elements (Reynolds et al. 2012) -->
<!-- ### Membership design: how locations are selected -->
<!-- #### Spatially-balanced sampling -->
<!-- ##### Balanced acceptance sampling (BAS; Robertson et al. 2013) -->
<!-- [`SDraw`](https://github.com/tmcd82070/SDraw) -->

<!-- ##### Generalized random tessellation stratified (GRTS; Stevens and Olsen 2003, 2004) -->
<!-- [`spsurvey`](https://github.com/cran/spsurvey)  -->

<!-- ### Response design: what to measure and how -->
<!-- ### Revisit design: schedule for visiting locations -->
