---
title: "Welcome to the Uplands Analytical Workshop!"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=FALSE, message=FALSE)
```

National Park Service (NPS) Inventory and Monitoring (I&M) networks are charged with implementing a long-term ecological monitoring program to assess status and trends in the condition of natural resources across NPS units. This website summarizes the support provided by CSP through several use cases involving models specified to both simulated and actual I&M datasets. 

### Hands-on analysis
The materials stored within the [GitHub repo](https://github.com/lzachmann/sevilleta-workshop-tester) for the workshop are accessible by two means:

1. [Connect to the Azure DSVM](#option1); or
2. [Configure everything yourself](#option2).

The first and _recommended_ option entails connecting to a virtual machine (VM) that has been pre-configured with all of the necessary software. Alternatively, you can configure everything yourself (requires some know-how and might be a two-beer job), and run code, including demos, locally. Both options are described in more detail below.   

Before proceeding, please [fork the repo](https://help.github.com/articles/fork-a-repo/). You'll use your fork of the repository to contribute data and code for analyses. Later on, I can pull your changes into the original repository/ 

<br>

#### Connect to the Azure DSVM {#option1}
Use x2goclient to connect to a Linux Data Science Virtual Machine (DSVM). This virtual machine contains popular tools for data science and development activities. We've used a shared instances architecture for the DSVM. You'll get the VM OS login credentials from us prior to the workshop. 

1. Connect to the VM^[If using x2goclient for the first time, please refer to the [X2Go instructions](#x2goconfig) before proceeding.]
2. In Terminal, navigate to (and create, if necessary) your working directory. Especially if you're using it as a scratch workspace, this directory can be placed _anywhere_ in your home directory. For example:  
```
$ mkdir sandbox
```
3. `cd` to your working directory and download the workshop materials by running a Git clone on command line:   
```
$ cd sandbox
$ git clone https://github.com/lzachmann/sevilleta-workshop-tester.git .
```
4. Activate the conda environment (called 'sev'):
```
$ source activate sev
```
5. Launch RStudio from inside this environment:  
```
$ rstudio
```
6. Make changes to project materials as appropriate on your instance, and push to your fork of the repository.  

<br>

#### Configure everything yourself {#option2}
Here you're on your own, but more power to you! A list of the known dependencies can be found in the `env.yml` file in the repo.

<br>

#### Other notes
#####  x2goclient configuration {#x2goconfig}
1. Download and install the X2Go client for your client platform from
[X2Go](http://wiki.x2go.org/doku.php/doc:installation:x2goclient)
2. Run the X2Go client, and select New Session
  * Configuration parameters:  
    - Host: 52.175.221.211  
    - Login: User name on the Linux VM  
    - SSH Port: Leave it at 22, the default value  
    - Session Type: Change the value to XFCE  
  * Media tab: Turn off sound support and client printing
  * Shared folders: If you want directories from your client machines mounted on the Linux VM, add the client machine directories that you want to share with the VM on this tab.
  
##### Git config
If you're going to commit anything to your fork of the repository, you'll need to set your user name and email address. 

```
$ git config --global user.email "you@example.com"
$ git config --global user.name "Your Name"
```
